Migration Fixes
getbread/goose pull request #7
Opened 2021-07-06 20:28 UTC by spencer-kormos-gbf

- Check migration files for dangling SQL. 
If there's incorrect sql after a `;` and before the next Goose comment block, it will be ignored without error.

- Check if local files are new and before current version.
If Susan creates a migration (e.g. `20210617000000_susans_migration.sql`) and Bobby creates a migration (e.g. `20210621000000_bobbys_migration.sql`) and Bobby submits their migration before Susan, Susan's migration will never run, and no error will raised.

2021-07-12 16:40 UTC, johnnyfeng-bread commented on lib/goose/migrate.go
> +	if pendingVersions, err := GetMissedMigrations(conf, db, current); err != nil {
This is using the migrations directory specified in `conf`, whereas elsewhere the migrations directory is pulled from the `migrationsDir` passed into `RunMigrations`. While, AFAICT, the migrations dir passed in is the same as the one specified in conf, it's probably a good idea to keep everything consistent and either
1. Pass `migrationsDir` along here and use it in `GetMissedMigrations`, or
2. Refactor `RunMigrations` to not accept the `migrationsDir` argument and pull migrationsDir from conf as well.

2021-07-12 16:40 UTC, johnnyfeng-bread commented on lib/goose/migrate.go
> +	rows, err := conf.Driver.Dialect.dbVersionQuery(conf.Table, db)
Would prefer to see us avoid an extra db hit here, I think ideally we would have something like a `ListMigrationRecords` query that returns all of the migrations in the goose table and that would be used by both this and EnsureDBVersion.

But since this only run when migrations are being run, it's not a blocking concern.

2021-07-12 16:40 UTC, johnnyfeng-bread commented on lib/goose/migrate.go
> +			dbMigrationVersionSet[record.VersionId] = struct{}{}
I think this is problematic with migrations that have been rolled back. The Goose table is append only, so when a migration is rolled back the original row is unchanged (with IsApplied set to true) and a new row is appended for that version with IsApplied set to false. With this implementation, I believe the most recent row will get ignored, but then the original row will still cause the version to get set here.

2021-07-12 16:40 UTC, johnnyfeng-bread commented on lib/goose/migrate.go
> +	localMigrationFiles, err := CollectMigrations(conf.MigrationsDir, int64(0), current)
SImilar to the extra db hit comment, I'd prefer to see a single call to collect the local migration versions and have that used where needed, so we're not making multiple unnecessary calls to the filesystem.

But this is, similarly, not run frequently enough to be a blocking concern.

2021-07-19 15:53 UTC, spencer-kormos-gbf commented on lib/goose/migrate.go
> +	localMigrationFiles, err := CollectMigrations(conf.MigrationsDir, int64(0), current)
I felt the same, but I really really really didn't want to add more work, and just modeled the change off of existing patterns.

2021-07-19 15:54 UTC, spencer-kormos-gbf commented on lib/goose/migrate.go
> +	rows, err := conf.Driver.Dialect.dbVersionQuery(conf.Table, db)
Same comment as the file system, also, didn't want to have parallel queries that might get altered differently and return different results that could create a different bug.

2021-07-19 16:12 UTC, spencer-kormos-gbf commented on lib/goose/migrate.go
> +	if pendingVersions, err := GetMissedMigrations(conf, db, current); err != nil {
Eh... thanks for flagging. I meant to change this. 

I'm incredibly wary of touching any existing method signatures, and was incredibly disappointed with the existing functions.

2021-07-19 16:12 UTC, spencer-kormos-gbf commented on lib/goose/migrate.go
> +			dbMigrationVersionSet[record.VersionId] = struct{}{}
Yeah, I wasn't 100% on what was going to happen here. This scenario will be tested for sure.

2021-07-21 16:34 UTC, johnnyfeng-bread commented on lib/goose/migrate.go
> +			dbMigrationVersionSet[record.VersionId] = struct{}{}
If you test this scenario out and it works, I'll drop the blocking review, but I'm pretty sure this is going to cause issues for the reasons mentioned, and accounting for this is why the `toSkip` list was needed in the original `EnsureDBVersion` logic.

2021-07-21 16:35 UTC, johnnyfeng-bread requested changes
Need to fix logic to skip detection of migrations that have been rolled back and are no longer active, or verify that it's not an issue.

2021-08-24 03:25 UTC, spencer-kormos-gbf commented
Closing this PR. 
1. There's a lot of work to test the changes.
2. There's not a high enough confidence with the changes tested, that they would still satisfy all existing use-cases, and there's not a lot of desire to support multiple versions of a 5 year old version of the library.
3. Alternative migration tools are actively being explored, and the changes will likely be moot by the time Bread adopts a new migration tool.

2021-08-24 03:25 UTC, closed without merging